### ISSUE TITLE
Order of default vs required

### ISSUE THREAD

**Issue by atomictag** [leadpony/justify#15]
This is mostly a question and not really an issue - it's actually probably the correct behaviour but I would appreciate your thoughts. When a property is _required_ AND has a _default_ sub-schema, the validator _first_ reports the error of missing required and _then_ applies the defaults. A schema like

```
{
   "properties" : {
        "foo" : { "type" : "string", "default" : "me foo!" }
   },
   "required" : ["foo"]
}
```
with `{}` as input data produces a _"missing required property foo"_  error but the resulting object is (in my mind, correctly) set to `{ "foo" : "me foo!" }`. I often resort running the validation twice - once to apply all defaults while ignoring errors and a second time to actually validated the input, completed with all default. It would be a useful feature to apply defaults first and then validate `required` constraints.

**Comment by leadpony** [comment]
@atomictag 
This behaviour is specified in the JSON Schema specification and the official test suite. The existence of `default` keyword must not change the result of validation, because support of `default` keyword is optional for validator implementation.

**Comment by atomictag** [comment]
Thanks for the clarification!
