### ISSUE TITLE
Localization for problems doesn't seem to work.

### ISSUE THREAD

**Issue by adreviko** [leadpony/justify#17]
Hi, thank you for this awesome project. I'm currently trying to add localization support to our validations. But it doesn't seem to work.

I've created a custom `ProblemHandler` to handle problems and return errors to our users. In the problem handler I'm retrieving messages for each problem in a similar way to this:

```
@Override
public void handleProblems(List<Problem> problems) {
    problems.forEach(problem -> LOGGER.error(problem.getMessage(locale)));
}
```

`locale` being a field in my `ProblemHandler` implementation.
I accept the `Locale` through `Accept-Language` header in my requests.

It seems that whichever locale I'm trying to send in I always get back english. Am I doing something wrong? I'm using `0.15.0` version of justify.

Thank you for your response.

**Comment by leadpony** [comment]
@adreviko  Thank you for trying this library.
I have added a small test in the commit 4f6e322 as below, and it seems to work fine.
```java
    @Test
    public void getMessage_shouldReturnDifferentMessageByLocale() {
        Problem problem = createProblem(SCHEMA, INSTANCE);
        String message1 = problem.getMessage(Locale.ENGLISH);
        String message2 = problem.getMessage(Locale.JAPANESE);

        assertThat(message1).isNotEmpty();
        assertThat(message2).isNotEmpty();
        assertThat(message1).isNotEqualTo(message2);
    }
```
The current implementation includes messages only for English and Japanese. If you need other languages, I must add translated messages as resource files of this library.
Thank you.

**Comment by adreviko** [comment]
Hi @leadpony, yes you are correct I've tried with japanese as specified language and it works correctly. Thank you for your help. At the moment we still don't know which languages will be supported in our product.
