### ISSUE TITLE
JsonValidatingException#getMessage show only the first problem message

### ISSUE THREAD

**Issue by gustabart** [leadpony/justify#23]
First of all, thanks for the library, it is very good and useful for my work.

**The code:**
```java
    @Override
    public String getMessage() {
        return getProblems().stream()
                .map(Problem::getContextualMessage)
                .collect(Collectors.joining("\n"));
    }
```
**The problem:**
When getProblems() has an only CompositeProblem, the method always return: 	
**Exactly one of the following sets of problems must be resolved.**

But in reality the useful messages are in the list of branches of the problem.
I think that getMessage should return all messages in depth, something similar to how ProblemPrinter works.
What do you think?

Gustavo.

**Comment by leadpony** [comment]
Hello @gustabart 
Thank you for contacting me.
I agree with you that it is better for  `JsonValidatingException#getMessage()` to  return a message describing all problems including problems on any branch.   
I reproduced the problem using the added test in the last commit.
Please give me time to think how to improve the implementation.
Thank you.

**Comment by gustabart** [comment]
Great, thanks!

**Comment by leadpony** [comment]
1.1.0 has been released, which fixes this issue.
