### ISSUE TITLE
Couple of basic questions

### ISSUE THREAD

**Issue by nik0la-vr** [leadpony/justify#30]
Hi.

1. It's not possible to pass json and schema as strings, I have to use something like this?

```
InputStream stream= new ByteArrayInputStream(schema.getBytes(StandardCharsets.UTF_8));
JsonSchema jsonSchema = service.readSchema(stream, StandardCharsets.UTF_8);
```

2. How to get boolean as a result, true or false if json is valid or not?

3. How to return list of problems from my method where validation is performed?

**Comment by leadpony** [comment]
Hi @nik0la-vr 
The following method returns whether the given JSON is valid or not as a boolean value. Both the JSON and the JSON schema are specified as string type.
```java
    private static JsonValidationService service = JsonValidationService.newInstance();

    public static boolean validateJson(String schemaAsString, String jsonAsString) {
        JsonSchema schema = service.readSchema(new StringReader(schemaAsString));
        List<Problem> problems = new ArrayList<>();
        ProblemHandler handler = ProblemHandler.collectingTo(problems);
        try (JsonReader reader = service.createReader(new StringReader(jsonAsString), schema, handler)) {
            reader.readValue();
        }
        return problems.isEmpty();
    }
```

In Java, you can pass an instance of `StringReader` to any method accepting `Reader`.
I believe you can easily modify the code above to return the list of problems found  in the validation.

**Comment by nik0la-vr** [comment]
Thanks.
