### ISSUE TITLE
Localization support for messages reported as part of callback in the ProblemHandler

### ISSUE THREAD

**Issue by maheshcamath** [leadpony/justify#39]
I want to localize the messages reported as part of the problem handler.
Is localization support available in justify ?

**Comment by leadpony** [comment]
Hello @maheshcamath 
Thank you for contacting me.
All of the messages for reporting the problems are defined in the properties file `messages_<locale>.properties` in the package [org.leadpony.justify.internal](https://github.com/leadpony/justify/tree/master/justify/src/main/resources/org/leadpony/justify/internal) .
If your application is running under *classpath*, you can put the localized properties file in the package named as `org.leadpony.justify.internal` directly in your jar file and Justify will pick it up.
Meanwhile, If your application is running under *module path*, unfortunately there is no way to provide the localized properties file for Justify of the current version.
Please see also #34

**Comment by maheshcamath** [comment]
Thanks a lot.
