### ISSUE TITLE
CLI needs a way to resolve remote schema references

### ISSUE THREAD

**Issue by kerrykimbrough** [leadpony/justify#4]
The CLI is a great tool for ad-hoc testing. But I'm hitting a snag with a schema that contains `$ref`s to other schema, which the CLI is unable to resolve. Some kind of command line option to define a simple resolver would be great. For example, options to define mappings between `$id` values and content URLs (including local files).

**Comment by leadpony** [comment]
Hello @kerrykimbrough.
Complex schemas are often modularized to multiple files. I will add the feature to the CLI soon. 
Thank you for your suggestion.

**Comment by leadpony** [comment]
Hello @kerrykimbrough.
 I have completly revised the CLI, which now has the following syntax.
```bash
justify [options] -s <path/to/JSON-schema> -i <path/to/JSON-instance> ...
```
There are two ways to specify additional schemas to be referenced.

1. Using `-r` option
    The `-r` option takes one or more schemas to be referenced like this:
    ```bash
    justify -s foo.schema.json -i bar.json -r baz.schema.json 
    ```
2. Using `-catalog` option
    The `-catalog` option takes a path to _schema catalog_ as follows:
    ```bash
    justify -s foo.schema.json -i bar.json -catalog baz.catalog.json 
    ```
    The schema catalog must be a JSON object and each property in the object corresponds to a JSON schema to be referenced. Its key is an ID and the value is a path or URL of the referenced schema.

Please find the attached file which contains the latest CLI as a release candidate:
[justify-cli-0.13.0-SNAPSHOT.zip](https://github.com/leadpony/justify/files/2898029/justify-cli-0.13.0-SNAPSHOT.zip)
Could you please test it with your schemas and instances? Any feedback is helpful for me.
Thank you so much for your suggestion.

**Comment by kerrykimbrough** [comment]
I'm having trouble with the `-r` option. Maybe I just don't understand how it's supposed to work.

For example, see attached files. This contains an instance named "find-Project.json", to be validated against the schema named "schema/project-schema.son", which references the schemas in the "others" directory.

But when I run the following command, it always complains that exactly one of the other schemas (generators-schema.json) can't be resolved. When I construct an equivalent schema catalog, all is good.

```
justify -s schema/project-schema.json -i find-Project.json -r others/{generators,system-input,system-test}-schema.json
```

[find-Project.zip](https://github.com/leadpony/justify/files/2902235/find-Project.zip)

**Comment by leadpony** [comment]
Thanks @kerrykimbrough for your quick evaluation.
The "$ref" keyword takes the "$id" value of other schema as follows.
```
"$ref": "http://www.cornutum.org/tcases/system-input-schema.json"
```
Please find the attached file which contains the "project-schema.json" with revised "$ref"s.
[find-Project.zip](https://github.com/leadpony/justify/files/2902563/find-Project.zip)
Thank you so much.

**Comment by leadpony** [comment]
Sorry, your original schema is right. 
I will examine the problem one more time and  contact you later.

**Comment by leadpony** [comment]
Hello again @kerrykimbrough.
"project-schema.json" has `$ref` keyword whose value is "generators-schema.json", which will be converted into "http://www.cornutum.org/tcases/generators-schema.json" as the asbolute URI.
On the other hand,  "generators-schema.json" has `$id` keyword whose value is "http://www.cornutum.org/tcases/generators.json".
Both are very close but not the same. I suppose the latter should be "http://www.cornutum.org/tcases/generators-schema.json" to be resolved.

I have revised the CLI a little bit to print the found ID of each referenced schema.
Please find the attached file containing the revised CLI as a release candidate.
[justify-cli-0.13.0-SNAPSHOT.zip](https://github.com/leadpony/justify/files/2905418/justify-cli-0.13.0-SNAPSHOT.zip)
Thank you so much.

**Comment by kerrykimbrough** [comment]
Oops, I missed that typo. Thanks for spotting it!

**Comment by kerrykimbrough** [comment]
The new RC looks good.

**Comment by leadpony** [comment]
Thank you for testing with your materials. I will release it officially in a few days.

**Comment by leadpony** [comment]
I have released the new CLI.
