### ISSUE TITLE
No support Jdk 8?

### ISSUE THREAD

**Issue by yohanyflores** [leadpony/justify#50]
I am trying to use version 3.0.0-RC1. But using jdk-8 I get this error:

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/leadpony/justify/api/JsonValidationService has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by leadpony** [comment]
@yohanyflores 
Thank you for reporting the issue.
Java 8 should be still supported. I will examine why it happens.

**Comment by leadpony** [comment]
@yohanyflores 
I tested the version 3.0.0-RC1 with Oracle JDK 8 and found it runs without error.  Did you retrieve the artifact from the Maven Central?

**Comment by yohanyflores** [comment]
@leadpony, Thanks for your quick response!

The artifact, I really hope, that you are getting it from "Maven Central".

However, when checking the version of my copy in .m2, with the following command:

```
javap -cp ~/.m2/repository/org/leadpony/justify/justify/3.0.0-RC1/justify-3.0.0-RC1.jar  -verbose org.leadpony.justify.api.JsonValidationService  | grep "major"
```

The output is:

```
major version: 53
```


So I downloaded the artifact that is in central maven and executing this command:

```
javap -cp ~/Downloads/justify-3.0.0-RC1.jar  -verbose org.leadpony.justify.api.JsonValidationService  | grep "major"        
```

The output is:

```
  major version: 52
```

So, I don't think I'm getting the artifact from "Maven Central".

I must check that!

Thank you!
