### ISSUE TITLE
Required Properties in the schema are not honored

### ISSUE THREAD

**Issue by borgogelli** [leadpony/justify#57]
[Required Properties](https://json-schema.org/understanding-json-schema/reference/object.html#required-properties) in the schema, are not honored when I specify a key which is missing in the data file

```
....
  "required": [
    "myFakeKey"
  ] 
```
So the validator doesn't return any error even if the "myFakeKey" is not present in the json data file;

**Comment by leadpony** [comment]
@borgogelli 

_issue57.schema.json_
```json
{
    "required": ["myFakeKey"]
}
```
_issue57.json_
```json
{
}
```
I tested them by using Justify-CLI 3.0.0-RC2 as follows:
```
justify -s issue57.schema.json -i issue57.json
```
This command outputs the following  result.
```
Validating the schema "issue57.schema.json"...
Justified the correctness of the schema "issue57.schema.json".
Validating the instance "issue57.json"...
[2,1][] The object must have a property whose name is "myFakeKey".
At least 1 problem(s) were found in the instance "issue57.json".
```
More information is needed to help you.

**Comment by borgogelli** [comment]
Thank you, It's my fault sorry but I would have expected an exception as result.
