### ISSUE TITLE
Determine the index of a non-compliant object in an array when validating against a schema

### ISSUE THREAD

**Issue by adityamandhare** [leadpony/justify#7]
When we are validating an array of objects agains a schema, and one or more of the objects are not compliant to the schema, there should be a way to determine the indexes of these non-compliant objects.

**Comment by adityamandhare** [comment]
Hello thank you for the support. Do you have a tentative date for the new release with the JSON pointer feature?

**Comment by leadpony** [comment]
Hello @adityamandhare .
Please try 0.14.0 now available in the Maven Central Repository.
If you encounter some difficulties in the new release, please open a new issue.
Thank you for contacting me.
