### ISSUE TITLE
How to use JSON strings instead of JSON locations when checking

### ISSUE THREAD

**Issue by tygithub1** [leadpony/justify#8]
Please provide examples as soon as possible. Thank you.

**Comment by leadpony** [comment]
Hello @tygithub1.
Do you mean you would like to use [JSON pointers](https://tools.ietf.org/html/rfc6901) instead of [JSON locations](https://static.javadoc.io/javax.json/javax.json-api/1.1.3/javax/json/stream/JsonLocation.html) when checking the reported problems in your program?

**Comment by leadpony** [comment]
I am sorry but I cannot understand your question. What do you mean by *JSON strings* in your question? Please provide me with more details about what you really want to achieve.
Thank you.

**Comment by tygithub1** [comment]
Hello big man
I am a rookie ,Maybe my description is not clear,now ,I want to validate a network resource that may be in JSON format. I don't think I should write this JSON data into the file every time, but should process it through the corresponding JSON api. So I think you should provide an interface to validate whether a string in JSON format conforms to my definition of JSON schema. Um.Refer to this address
Https://github.com/java-json-tools/json-schema-validator,
thanks!

**Comment by leadpony** [comment]
Hello @tygithub1. 

It's easy to achive. 
Please see the following code sample shown in README.md with small modification.
```java
JsonValidationService service = JsonValidationService.newInstance();

// Reads the JSON schema from file
JsonSchema schema = service.readSchema(Paths.get("your.schema.json"));

// Problem handler which will print problems found.
ProblemHandler handler = service.createProblemPrinter(System.out::println);

String json = " ... your JSON to be validated here ... ";
// Reads the JSON instance from the string above
try (JsonReader reader = service.createReader(new StringReader(json), schema, handler)) {
    JsonValue value = reader.readValue();
    // Do something useful here
}
```
Your can use [StringReader](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/io/StringReader.html) as a reader of JSON instance in a string. The instance of `StringReader` can be passed to `JsonValidationService#createReader()` or `JsonValidationService#createParser()`as the first parameter.

Thank you.

**Comment by tygithub1** [comment]
Wow, I just tried it. Very good. Thank you very much.
